version: "1.0"
name: cinedle-backend

volumes:
  postgres_data:

services:
  postgres:
    container_name: cinedle_postgres
    image: postgres:17.5
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=cinedle